### Importando libreria NUMPY

In [2]:
import numpy as np

#### Creando lista de 10 elementos

In [3]:
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando lista a array

In [4]:
arreglo= np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Corroborando el tipo de estructura

In [5]:
type(arreglo)

numpy.ndarray

### Corroborando el tipo de datos del arreglo

In [6]:
arreglo.dtype #entero de 32 bits

dtype('int32')

### Definiendo el Array de int32 a float32

In [7]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

### Transformando los datos de int32 a float32

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

### Obteniendo promedio del array

In [9]:
promedio= np.mean(arreglo)
promedio

5.5

### Obteniendo mediana del array

In [10]:
mediana= np.median(arreglo)
mediana

5.5

### Desviacion estandar del arreglo

In [11]:
desviacion_std= np.std(arreglo)

### Funcion similar a Range pero con arrays

In [12]:
arreglonuevo=np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Lista de 2 en 2 con arange

In [13]:
arreglonuevo2=  np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

### Generacion de un arreglo de 10 elementos de solo unos

In [25]:
arreglo_de_unos= np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Transformando el arreglo de unos de punto flotante a enteros

In [ ]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

### Generacion de un arreglo de 10 elementos de solo ceros 

In [ ]:
arreglo_de_ceros= np.zeros(5)
arreglo_de_ceros

### Generando un arreglo aleatorio de 5 elementos

In [ ]:
arreglo_aleatorio= np.random.rand(5)
arreglo_aleatorio

### Generando arreglo aleatorio de enteros del 1 al 5

In [21]:
arreglo_aleatorio2= np.random.randint(1,1001,10)
arreglo_aleatorio2

array([222, 327,  53, 535, 193,  32, 584, 612, 749, 469])

### Matriz aleatoria de 3x3 (Matriz= anidacion de listas en filas y columnas)

In [22]:
matriz=np.random.rand(3,3)
matriz

array([[0.18885932, 0.43882067, 0.32523046],
       [0.48625551, 0.61254951, 0.75432219],
       [0.81005654, 0.06873829, 0.60806529]])

### Matriz aleatoria de numeros enteros del 10 al 100

In [24]:
matriz2= np.random.randint(1,100,(10,10))
matriz2

array([[76, 11, 78, 43, 77,  2, 49, 18, 70,  6],
       [38, 81, 85, 42, 93,  7, 43, 52, 66, 91],
       [19, 55, 89, 52, 63, 32, 90, 59, 53, 95],
       [60, 51, 49, 55, 58, 62, 41, 41, 19, 66],
       [47, 35, 67, 50, 34,  7,  6, 10, 98, 85],
       [19, 62, 33, 67, 48, 82,  4, 36, 21, 75],
       [93,  7, 36, 88, 43, 62, 55, 94, 82, 19],
       [57, 13, 23, 93, 18, 74, 96, 94, 48, 56],
       [55, 56, 49, 42, 58, 75, 41, 65, 65, 80],
       [38, 54, 99, 63, 85, 52,  2, 20, 80, 53]])