### Dimensiones

In [2]:
import numpy as np

### Generando arreglo de 12 elementos con random

In [10]:
arreglo = np.random.randint(1,10,12)
arreglo

array([5, 6, 7, 2, 7, 3, 2, 6, 6, 4, 1, 6])

### Obtener dimension de un arreglo

In [11]:
np.shape(arreglo)

(12,)

### Transformacion del vector de 9 elementos a matriz 4x3 y 3x4 con Reshape

In [12]:
matriz = arreglo.reshape(4,3)
matriz

array([[5, 6, 7],
       [2, 7, 3],
       [2, 6, 6],
       [4, 1, 6]])

In [13]:
matriz = arreglo.reshape(3,4)
matriz

array([[5, 6, 7, 2],
       [7, 3, 2, 6],
       [6, 4, 1, 6]])